name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Root Dependencies
        run: npm ci

      - name: Install Functions Dependencies
        run: npm ci
        working-directory: ./functions

      - name: Build Frontend Project
        run: npm run build
        env:
          VITE_MAPS_KEY: ${{ secrets.VITE_MAPS_KEY }}
          VITE_FIREBASE_CLIENT_CONFIG: '${{ secrets.FIREBASE_CLIENT_CONFIG }}'

      - name: Build Functions Project
        run: npm run build
        working-directory: ./functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive
